[package]
name = "Moverr"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-logger = "0.14.0"
tui-menu = "0.3.0"
log.workspace = true
windows.workspace = true
num-format = "0.4.4"
async-fs = "2.1.2"
futures-lite.workspace = true
smol = "2.0.2"
futures-concurrency = "7.6.2"

[build-dependencies]
embed-manifest = "1.4.0"
